language: c
dist: focal
os: linux

compiler:
  - gcc

before_install:
  # Install a supported cmake version (>= 3.14)
  - wget -O cmake.sh https://cmake.org/files/v3.14/cmake-3.14.0-Linux-x86_64.sh
  - sudo sh cmake.sh --skip-license --exclude-subdir --prefix=/usr/local
  - export PATH=/usr/local/bin:$PATH
  - cmake --version

script:
  - ./build.sh

addons:
  apt:
    packages:
    - cmake
    - libcapstone-dev
    - mono-devel
